Home Office API Guide for Developers
====================================
:toc:
:numbered:
:toc-placement!:

toc::[]

== Introduction
This document is intended to help developers in the Home Office understand our current and recommended approaches for developing APIs

== Authentication
How consumers authenticate with an API is important for many APIs. Whilst we've not settled on a standard the following approaches have been tried.

=== Mutual TLS
Mutual TLS means that connecting clients need to have a client certificate before using the service. Typically the system terminating the mutual TLS will add headers to identify the client. The could allow your application to use these for example for granular permissions.

.Pros and Cons of Mutual TLS
|===
|Pros | Cons
|Can use standard nginx or similar for this purpose, so your application doesn't need to worry about auth
|Client certificates will expire, and hence need to recreate these for all clients periodically, which introduces a lot of overhead and potential for errors

|
|Have to maintain a CA for signing client certs
|===

=== OAuth2 with keycloak
OAuth2 is very commonly used for user authentication, but less frequently for API authentication. This is reflected by fewer client auth libraries available than you may expect. However the logic is trivial to implement.

We can implement OAuth2 authentication trivially using keycloak-proxy in front of an API, authenticating to a centralised keycloak server. This is especially beneficial as keycloak-proxy combined with a centralised keycloak give many capabilities for free such as role and user management, brute force prevention.

.Pros and Cons of OAuth2 with keycloak
|===
|Pros | Cons
|Can implement trivially using keycloak-proxy and keycloak
|Client auth is slightly more complicated

|Get a lot of capabilities for free with keycloak
|

|Possibility for consumers to rotate their own credentials, reducing administrative overhead
|

|Creds are only sent to the system on first auth or when the authentication token expires
|===

=== Basic HTTP Auth with username and password
Basic HTTP auth requires a username and password to be sent with every request.

.Pros and Cons of Basic HTTP Auth
|===
|Pros | Cons
|Very simple to set up initially
|Doing anything beyond basic auth is difficult

|
|User accounts have to be managed by your application, introducing complexity
|===

== Acceptance tests, documentation, and creating a mock of your API
These topics all go hand in hand - frequently one document can be the basis for tests, documentation, and for generating a mock. Here we will cover the common approaches we favour, and when each is appropriate.

=== Recommended approach - Rest-assured tests with Spring RestDocs (you don't need Spring!), and Wiremock

*Why we like this approach*

* It enables one set of tests to generate docs and mock, helping to make sure everything ties together
* The mock generated is flexible - it can have multiple canned responses per endpoint depending on the request params, whereas many other automatically generated mocks only allow one canned response per endpoint
* The docs generated are flexible - A person writes the overall documentation, meaning it can be structured however makes most sense for your API, with as much detail as you like. The generated snippets then give real examples that you can embed into sections. This allows you to put much more context around the documentation than you may otherwise have been able to do
* Allows testing and documentation of a json schema for your API

*Example application using this approach* +
https://ukhomeoffice.github.io/lev-api-docs/[Example docs] and https://github.com/UKHomeOffice/lev-api-docs/tree/master/mock[mock] for the LEV project are available here.

https://gitlab.digital.homeoffice.gov.uk/lev/lev-api-scala[Code] is available here (you may need to ask a member of the LEV team for access).

If you have any questions ask in the developers slack channel and one of us will get back to you.

*https://github.com/rest-assured/rest-assured[Rest-assured]* +
Rest assured is a library designed for making testing APIs straightforward. We recommend it here as it works out the box with Spring RestDocs.

*http://projects.spring.io/spring-restdocs/[Spring Restdocs]* +
Spring Restdocs allows you to generate documentation snippets for each of your tests. It records the request and the response and creates snippets for each of these. You can then embed these snippets into a master document that describes your whole API.

Documentation snippets are recorded in asciidoctor format, which is like a more advanced version of markdown. The main readme asciidoc file can then embed snippets from other files

*http://wiremock.org/[Wiremock]* +
Wiremock is a mock API that allows you to record a series of requests and responses (by proxying requests through wiremock). When running your rest-assured tests you should proxy requests through a wiremock instance in record mode. It will then generate a number of files that represent the requests and responses. These files can then be used to run wiremock as a mock, where it will then respond with the recorded responses.

=== Alternative approach - http://swagger.io/[Swagger]
Swagger is a very common way to document APIs. It does a reasonable job of getting some API documentation available. The shortcomings are that it can become out of sync (it relies heavily on annotations which can get out of date), the mock you can generate from a swagger spec is very inflexible, and the docs are also very inflexible. The major benefits are that it is a common format that you can put together very quickly.

=== Alternative approach - https://apiblueprint.org/[API Blueprint]
API blueprint allows you to have one markdown file which is a specification of your API. From this file you can generate html docs, run tests, and generate a mock version of your API. The shortcomings are that the mock you can generate from an API Blueprint is very inflexible, and the docs are also very inflexible. The major benefits are that it is a common format that you can put together very quickly.

== Technologies for building APIs
This will never be a conclusive list, but just says what technologies we have found good and bad for building APIs, and when we would recommend each of them.

== API Versioning
This section will detail our approach to API versioning. Please note though having to version an API is never a desirable thing and should be avoided if possible using the strategy of expanding and contracting APIs (contracting once all clients have migrated away from old functionality).

== API Gateways
Currently still something we are looking into, so consider this a placeholder for thoughts on API Gateways
